/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "ubtkdilrvivwoqgtgyqg"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVidGtkaWxydml2d29xZ3RneXFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMyNDIxMjEsImV4cCI6MjA3ODgxODEyMX0.wQ-XvrRuM82DScTM24iSqJFrKjhXTLu8eNc-LDwz8Uk"